/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.util.ServiceLoader;

import libone.LibOneApi;
import libtwo.LibTwoApi;

public class App {

    public static void main(String[] args) {
        final ServiceLoader<LibOneApi> libOneServices = ServiceLoader.load(LibOneApi.class);
        final ServiceLoader<LibTwoApi> libTwoServices = ServiceLoader.load(LibTwoApi.class);

        libOneServices.forEach(LibOneApi::someLibraryMethod);
        libTwoServices.forEach(LibTwoApi::someLibraryMethod);

        //
        // Cannot use these hidden packages and classes, the
        // Java module system disallows it at compile time and
        // run time.
        //
        // hidden.libone.Hidden.doLibOneHiddenWork();
        //hidden.libtwo.Hidden.doLibTwoHiddenWork();

        System.out.println(new App().getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
