/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

public class App {

    public static void main(String[] args) {
        new libone.Library().someLibraryMethod();
        new libtwo.Library().someLibraryMethod();
        System.out.println(new App().getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
