/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hidden.libone;

import libone.LibOneApi;

public class Library implements LibOneApi {
    public Library() {
    }

    public boolean someLibraryMethod() {
        Hidden.doLibOneHiddenWork();
        return true;
    }
}
