/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libtwo;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("libtwo.Library :-)");
        return true;
    }
}
