/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libtwo;

import hidden.libtwo.Hidden;

public class Library {
    public boolean someLibraryMethod() {
        Hidden.doLibTwoHiddenWork();
        return true;
    }
}
