/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libone;

import hidden.libone.Hidden;

public class Library {
    public boolean someLibraryMethod() {
        Hidden.doLibOneHiddenWork();
        return true;
    }
}
