/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libone;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("libone.Library!");
        return true;
    }
}
