/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hidden.libtwo;

import libtwo.LibTwoApi;

public class Library implements LibTwoApi {
    public boolean someLibraryMethod() {
        Hidden.doLibTwoHiddenWork();
        return true;
    }
}
